// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Circuit's syntax palette is fixed across the whole family (see
// @erisera-code/circuit's src/tokens.css) — reused verbatim so code reads
// identically here and on the erisera product sites.
const circuitShikiTheme = {
  name: 'circuit',
  type: 'dark',
  colors: {
    'editor.background': '#0f172a',
    'editor.foreground': '#e2e8f0',
  },
  tokenColors: [
    { scope: ['comment'], settings: { foreground: '#8b93a1', fontStyle: 'italic' } },
    { scope: ['string', 'string.quoted'], settings: { foreground: '#0f9d63' } },
    { scope: ['keyword', 'keyword.control', 'storage.type', 'storage.modifier'], settings: { foreground: '#d6337d' } },
    { scope: ['entity.name.function', 'support.function'], settings: { foreground: '#1d6fbf' } },
    { scope: ['constant.numeric'], settings: { foreground: '#9333d6' } },
    { scope: ['entity.name.tag', 'meta.tag'], settings: { foreground: '#b45f06' } },
    { scope: ['entity.other.attribute-name'], settings: { foreground: '#1d8f8f' } },
    { scope: ['entity.name.type', 'entity.name.class', 'support.type', 'support.class'], settings: { foreground: '#7c4fd6' } },
    { scope: ['constant.language', 'constant.language.boolean'], settings: { foreground: '#c0392b', fontStyle: 'bold' } },
    { scope: ['punctuation', 'punctuation.definition', 'punctuation.separator'], settings: { foreground: '#94a3b8' } },
  ],
};

export default defineConfig({
  site: 'https://opensource.johnhenry.me',
  integrations: [
    starlight({
      title: 'John Henry · Open Source',
      description:
        'Documentation for John Henry\'s open-source JavaScript libraries and tools.',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/johnhenry' },
      ],
      favicon: '/favicon.svg',
      customCss: ['./src/styles/circuit-bridge.css'],
      components: { Head: './src/components/Head.astro' },
      expressiveCode: { themes: [circuitShikiTheme] },
      // Starlight v0.39 removed autogenerated groups as a top-level sidebar
      // entry — the autogenerate config now goes inside a group's `items`.
      sidebar: [
        { label: 'Overview', link: '/' },
        ...[
          { label: 'ai.matey', directory: 'ai-matey' },
          { label: 'Agent Query', directory: 'agent-query' },
          { label: 'Math', directory: 'math' },
          { label: 'ecmanim', directory: 'ecmanim' },
          { label: 'http-fields', directory: 'http-fields' },
          { label: 'wsh', directory: 'wsh' },
          { label: 'Optical Artifact Transport', directory: 'oat' },
          { label: 'andbox', directory: 'andbox' },
          { label: 'objectify', directory: 'objectify' },
          { label: 'Circuit', directory: 'circuit' },
          { label: 'jth', directory: 'jth' },
          { label: 'temporals', directory: 'temporals' },
          { label: 'semantic-chunker', directory: 'semantic-chunker' },
          { label: 'spintax', directory: 'spintax' },
          { label: 'tester', directory: 'tester' },
        ].map(({ label, directory }) => ({
          label,
          collapsed: true,
          items: [{ autogenerate: { directory } }],
        })),
      ],
    }),
  ],
});
