export * as vector from "./core/math/vector.ts";
export * as bezier from "./core/math/bezier.ts";
export { ORIGIN, UP, DOWN, LEFT, RIGHT, IN, OUT, UL, UR, DL, DR, PI, TAU, DEGREES, } from "./core/math/vector.ts";
export * from "./core/color.ts";
export * as colors from "./core/color.ts";
export { effectsToCanvasFilter, effectPad, effectsFingerprint, splitEffects, makeNoiseBytes, saturateMatrix, hueRotateMatrix, lerpEffects, } from "./core/effects.ts";
export type { Effect, FrameEffect } from "./core/effects.ts";
export { X_AXIS, Y_AXIS, Z_AXIS, TOP, BOTTOM, LEFT_SIDE, RIGHT_SIDE, SMALL_BUFF, MED_SMALL_BUFF, MED_LARGE_BUFF, LARGE_BUFF, DEFAULT_MOBJECT_TO_EDGE_BUFFER, DEFAULT_MOBJECT_TO_MOBJECT_BUFFER, FRAME_HEIGHT, FRAME_WIDTH, FRAME_X_RADIUS, FRAME_Y_RADIUS, DEFAULT_FRAME_RATE, EPSILON, DEFAULT_STROKE_WIDTH, DEFAULT_FONT_SIZE, DEFAULT_DOT_RADIUS, DEFAULT_ARROW_TIP_LENGTH, RendererType, LineJointType, CapStyleType, } from "./core/constants.ts";
export * as constants from "./core/constants.ts";
export { Mobject, Group, CompositeGroup } from "./mobject/Mobject.ts";
export { VMobject, VGroup } from "./mobject/VMobject.ts";
export { Arc, Circle, Dot, Ellipse, Annulus, Line, DashedLine, Arrow, Polygon, RegularPolygon, Triangle, Rectangle, Square, } from "./mobject/geometry.ts";
export * from "./mobject/tips.ts";
export * from "./mobject/arcs.ts";
export * from "./mobject/polygram.ts";
export * from "./mobject/shape_matchers.ts";
export * from "./mobject/vectors.ts";
export * from "./mobject/labeled.ts";
export * from "./mobject/boolean_ops.ts";
export * from "./mobject/matrix.ts";
export * from "./mobject/table.ts";
export * from "./mobject/brace.ts";
export * from "./mobject/graph.ts";
export { Text, MarkupText, RasterText, CHAR_ASPECT, estimateTextSize, fontSizePt } from "./mobject/text/Text.ts";
export * from "./mobject/text/paragraph.ts";
export * from "./mobject/text/tex_extras.ts";
export * from "./mobject/text/code.ts";
export * from "./mobject/text/variable.ts";
export { ChangingDecimal, ChangeDecimalToValue } from "./animation/numbers.ts";
export { VText, setDefaultFont, setDefaultFontSync, getDefaultFont } from "./mobject/vectorized_text.ts";
export { setTextShapingBackend, getTextShapingBackend, isTextShapingBackendActive, buildGlyphRun, measureGlyphRunWidth, } from "./mobject/text_shaping.ts";
export type { TextShapingBackend, GlyphRunEntry, GlyphRunResult, BuildGlyphRunOptions } from "./mobject/text_shaping.ts";
export { parsePathToSubpaths, subpathsToVMobject } from "./mobject/svg_path.ts";
export { MathTex, Tex, SingleStringMathTex, texToVGroup, initMathTex, texToSVG, glyphsFromDomSvg, matchTex, parseTexGroups } from "./mobject/mathtex.ts";
export type { MatchTexResult } from "./mobject/mathtex.ts";
export { CubicBezier, QuadBezier, Spline, Path, PolyLine } from "./mobject/curves.ts";
export type { CubicBezierConfig, QuadBezierConfig, SplineConfig, SplinePoint, PathConfig, PolyLineConfig } from "./mobject/curves.ts";
export { MathTexImage, mathTexImage } from "./mobject/mathtex_image.ts";
export { ImageMobject } from "./mobject/image_mobject.ts";
export { VideoMobject } from "./mobject/video_mobject.ts";
export type { VideoFrameProvider, VideoMobjectConfig } from "./mobject/video_mobject.ts";
export { toVideoObject, toVideoObjectScript, toIIIFManifest, resolveIIIFVideo, isIIIFManifest, chaptersFrom, metaDuration, toISODuration, MANIM_JS_VERSION, IPTC_ALGORITHMIC_MEDIA, } from "./metadata.ts";
export type { VideoMetaInput, MetaSection, Chapter, ProvenanceInput, ResolvedIIIFVideo, } from "./metadata.ts";
export { SVGMobject, parseXML, parseTransform } from "./mobject/svg_mobject.ts";
export { ThreeDScene, ThreeDCamera, ThreeDAxes } from "./scene/three_d.ts";
export { MovingCameraScene, ScreenRectangle, FullScreenRectangle } from "./scene/moving_camera_scene.ts";
export type { CameraStop } from "./scene/moving_camera_scene.ts";
export { ZoomedScene, ZoomedDisplay } from "./scene/zoomed_scene.ts";
export { VectorScene, LinearTransformationScene } from "./scene/vector_space_scene.ts";
export { MultiCamera } from "./camera/multi_camera.ts";
export { MappingCamera } from "./camera/mapping_camera.ts";
export { Surface, ParametricSurface, Sphere, Torus, Cylinder, Cone, Box, Cube, Prism, Dot3D, Line3D, Arrow3D, ThreeDVMobject, } from "./mobject/surface.ts";
export { Polyhedron, Tetrahedron, Octahedron, Icosahedron, Dodecahedron, ConvexHull3D, } from "./mobject/polyhedra.ts";
export { loadMeshOBJ, extractMeshData, extractMeshDataFromGeometry, isMeshLoaderAvailable, } from "./loaders/mesh_obj.ts";
export type { MeshOBJImportOptions } from "./loaders/mesh_obj.ts";
export { loadMeshSTL } from "./loaders/mesh_stl.ts";
export type { MeshSTLImportOptions } from "./loaders/mesh_stl.ts";
export { Mesh3D } from "./mobject/mesh3d.ts";
export { loadMesh3D } from "./loaders/mesh3d_loader.ts";
export type { Mesh3DImportOptions } from "./loaders/mesh3d_loader.ts";
export { normalizePixelArray } from "./core/pixel_array.ts";
export type { NormalizedPixels } from "./core/pixel_array.ts";
export { loadGeoJSON, GeoMap } from "./loaders/geojson_loader.ts";
export type { GeoJSONOptions } from "./loaders/geojson_loader.ts";
export { mercator, equirectangular } from "./loaders/geo_projection.ts";
export type { GeoProjection } from "./loaders/geo_projection.ts";
export { NumberLine, Axes, NumberPlane, PolarPlane, ComplexPlane, UnitInterval } from "./mobject/coordinate_systems.ts";
export { reprojectCurve } from "./mobject/coordinate_reprojection.ts";
export type { CoordSystemLike, ReprojectOptions } from "./mobject/coordinate_reprojection.ts";
export * from "./mobject/functions.ts";
export * from "./mobject/probability.ts";
export { PieChart } from "./mobject/charts.ts";
export type { PieChartConfig } from "./mobject/charts.ts";
export { GaugeChart } from "./mobject/gauge.ts";
export type { GaugeChartConfig, GaugeBand } from "./mobject/gauge.ts";
export { Legend, ColorBar } from "./mobject/legend.ts";
export type { LegendItem, LegendConfig, ColorBarConfig } from "./mobject/legend.ts";
export { Candlestick } from "./mobject/candlestick.ts";
export type { CandlestickConfig, CandlestickPoint } from "./mobject/candlestick.ts";
export { FunnelChart } from "./mobject/funnel.ts";
export type { FunnelChartConfig, FunnelStage } from "./mobject/funnel.ts";
export { RadarChart } from "./mobject/radar.ts";
export type { RadarChartConfig, RadarIndicator } from "./mobject/radar.ts";
export { ParticleSystem } from "./mobject/particles.ts";
export type { ParticleSystemConfig, ParticleState } from "./mobject/particles.ts";
export { CellularAutomaton } from "./mobject/cellular_automaton.ts";
export type { CellularAutomatonConfig, CellularAutomatonRule } from "./mobject/cellular_automaton.ts";
export { SoftBodySimulation, SoftBody } from "./mobject/soft_body.ts";
export type { SoftBodyConfig, SoftBodyMobjectConfig } from "./mobject/soft_body.ts";
export * from "./mobject/vector_field.ts";
export * from "./mobject/graphing_scale.ts";
export { ValueTracker, DecimalNumber, Integer, alwaysRedraw } from "./mobject/value_tracker.ts";
export { FlexGroup, isYogaLoaded } from "./mobject/flex_group.ts";
export type { FlexGroupConfig, FlexChildConfig, FlexDirection, JustifyContent, AlignItems } from "./mobject/flex_group.ts";
export { CanvasRenderer, Camera } from "./renderer/CanvasRenderer.ts";
export { SVGRenderer, mobjectsToSVG } from "./renderer/SVGRenderer.ts";
export type { SVGRenderOptions } from "./renderer/SVGRenderer.ts";
export { Scene } from "./scene/Scene.ts";
export type { TaskHandle } from "./scene/Scene.ts";
export { Direction, slideTransition, fadeTransition, zoomInTransition, finishScene } from "./scene/scene_transitions.ts";
export { CameraFrameTween } from "./scene/moving_camera_scene.ts";
export type { IncomingContent, ZoomArea } from "./scene/scene_transitions.ts";
export { isSceneLike, makeScene, runConstruct, sampleSceneAt } from "./scene/orchestrate.ts";
export { Animation, Transform, ReplacementTransform, Create, Write, Uncreate, FadeIn, FadeOut, ApplyMethod, Shift, MoveTo, ScaleAnim, FadeToColor, } from "./animation/Animation.ts";
export { AnimationGroup, LaggedStart, LaggedStartMap, Succession, makeAnimateBuilder, } from "./animation/composition.ts";
export { GrowFromPoint, GrowFromCenter, GrowFromEdge, SpinInFromNothing, ShrinkToCenter, Rotating, Rotate, MoveAlongPath, Indicate, Flash, Wiggle, Circumscribe, FocusOn, } from "./animation/extra.ts";
export { DrawBorderThenFill, Unwrite, ShowIncreasingSubsets, ShowSubmobjectsOneByOne, AddTextLetterByLetter, RemoveTextLetterByLetter, AddTextWordByWord, TypeWithCursor, Untype, UntypeWithCursor, SpiralIn, } from "./animation/creation_extra.ts";
export { TransformFromCopy, ClockwiseTransform, CounterclockwiseTransform, MoveToTarget, Restore, ApplyFunction, ApplyPointwiseFunction, ApplyPointwiseFunctionToCenter, ApplyMatrix, ApplyComplexFunction, ScaleInPlace, FadeTransform, FadeTransformPieces, CyclicReplace, Swap, } from "./animation/transform_extra.ts";
export { TransformMatchingShapes, TransformMatchingTex, matchingParts } from "./animation/transform_matching.ts";
export { TransformMatchingAuto, autoMatchKeys } from "./animation/auto_matching.ts";
export { parseDiagram, layoutDiagram, buildBoard, diagram } from "./diagram/diagram.ts";
export type { DiagramGraph, DiagramNode, DiagramEdge, BoardOptions } from "./diagram/diagram.ts";
export { convert as py2ts } from "./tools/py2ts.ts";
export * from "./reactive/signal.ts";
export { Player, bindScroll, bindPlayerToScroll, computeScrollProgress } from "./player.ts";
export type { ScrollBindingOptions, ScrollBinding, ScrollProgressInput } from "./player.ts";
export { Homotopy, SmoothedVectorizedHomotopy, ComplexHomotopy, PhaseFlow } from "./animation/movement.ts";
export { ShowPassingFlash, ShowPassingFlashWithThinningStrokeWidth, ApplyWave, Blink } from "./animation/indication_extra.ts";
export { AnimatedBoundary, TracedPath } from "./animation/changing.ts";
export { Broadcast, ChangeSpeed, UpdateFromFunc, UpdateFromAlphaFunc } from "./animation/specialized.ts";
export { ComplexValueTracker } from "./mobject/complex_value_tracker.ts";
export * as rate_functions from "./animation/rate_functions.ts";
export { wiggle, remap, ramp, valueAtTime, compose, mulberry32 } from "./animation/expressions.ts";
export type { Driver } from "./animation/expressions.ts";
export { valueNoise1D, simplex2D, simplex3D, fbm, fbm3 } from "./core/noise.ts";
export { scaleLinear, scaleLog, scalePow, scaleSqrt, scaleRadial, scaleUtc, scaleTime, scaleBand, scalePoint, scaleOrdinal, scaleSequential, scaleDiverging, scaleQuantize, scaleThreshold, visualMapContinuous, } from "./core/scales.ts";
export type { ScaleLinear, ScaleTime, ScaleBand, ScaleOrdinal, ScaleSequential, ScaleQuantize, ScaleThreshold, VisualMapContinuous, VisualMapContinuousConfig, } from "./core/scales.ts";
export { ascending, descending, extent, max, min, sum, mean, rangeOf, quantile, movingAverage, group, groups, rollup, rollups, groupSort, pairs, ticks, tickStep, tickIncrement, niceExtent, } from "./core/array_utils.ts";
export { format, formatSpecifierAuto, utcFormat, utcDay, utcSunday, utcMonday, utcMonth, utcYear } from "./core/format.ts";
export type { UtcInterval } from "./core/format.ts";
export { schemeCategory10, schemeTableau10, schemeObservable10, schemeBlues, makeInterpolator, interpolateBlues, interpolateBuPu, interpolatePiYG, interpolateBrBG, interpolateSpectral, interpolateViridis, interpolateTurbo, interpolateRainbow, interpolateTerrain, interpolateHsvLong, interpolateHcl, hsv, } from "./core/color_schemes.ts";
export { stack, lineGen, areaGen, pieGen, arcShape, radialPoint, linkHorizontalPoints, linkVerticalPoints, linkRadialPoints, basisBeziers, bundleBeziers, bezierChainMobject, } from "./mobject/shape_gen.ts";
export type { StackSeries, StackConfig, PieSlice, ArcGenConfig, CurveKind } from "./mobject/shape_gen.ts";
export { hierarchy, stratify, treemap, partition, pack, tree, cluster, treemapSquarify, treemapBinary, treemapSlice, treemapDice, treemapSliceDice, packSiblings, packEnclose, HierarchyNode, } from "./layout/hierarchy.ts";
export type { HierarchyLink, TreemapLayout, PartitionLayout, PackLayout, TreeLayout, ClusterLayout } from "./layout/hierarchy.ts";
export { forceSimulation, forceLink, forceManyBody, forceCenter, forceCollide, forceX, forceY, } from "./layout/force.ts";
export type { ForceSimulation, SimulationNode, SimulationLink, Force } from "./layout/force.ts";
export { BoidsSimulation, boidsSimulation } from "./layout/boids.ts";
export type { BoidsConfig, BoidState } from "./layout/boids.ts";
export { BoidsFlock } from "./mobject/boids.ts";
export type { BoidsFlockConfig } from "./mobject/boids.ts";
export { sankey, sankeyLinkHorizontalPoints } from "./layout/sankey.ts";
export { chord, ribbonPoints, chordAngleToPoint } from "./layout/chord.ts";
export { contours, contourThresholds } from "./layout/contours.ts";
export { hexbin, hexagonPoints } from "./layout/hexbin.ts";
export { feature, mesh, decodeArc } from "./loaders/topojson.ts";
export type { Topology } from "./loaders/topojson.ts";
export { dataJoin, interpolateFrames, rankFrame } from "./animation/data_join.ts";
export { sieve, primesUpTo, isPrime, eigen2x2 } from "./core/math/primes.ts";
export { hilbertCurve, lsystem } from "./layout/hilbert.ts";
export { FourierPath, dftOfPath, samplePath } from "./mobject/fourier_path.ts";
export type { FourierCoefficient, FourierPathConfig } from "./mobject/fourier_path.ts";
export { NeuralNetworkMobject } from "./mobject/neural_network.ts";
export { loadMermaid, renderMermaidSvg, DiagramMobject } from "./loaders/mermaid_loader.ts";
export type { MermaidLoadConfig, MermaidRenderConfig, MermaidDiagramType } from "./loaders/mermaid_loader.ts";
export { revealDiagram, DiagramReveal, parseEdgeEndpoints } from "./animation/diagram_reveal.ts";
export type { DiagramRevealConfig } from "./animation/diagram_reveal.ts";
export { diffDiagrams, DiagramDiff } from "./animation/diagram_diff.ts";
export { parseDeckMarkdown, deckFromMarkdown } from "./loaders/deck_markdown.ts";
export type { DeckSlide, DeckCodeBlock, DeckConfig } from "./loaders/deck_markdown.ts";
export type { DiagramDiffConfig } from "./animation/diagram_diff.ts";
export { loadLottie, LottieMobject } from "./mobject/lottie_mobject.ts";
export { parseLottie, cubicBezierEase, evalProperty } from "./loaders/lottie_loader.ts";
export { loadASS, ASSMobject } from "./mobject/ass_mobject.ts";
export { parseASS, parseAssColor, parseAssTime, tokenizeOverrideText } from "./loaders/ass_loader.ts";
export type { ASSConfig } from "./mobject/ass_mobject.ts";
export type { ASSScript, ASSStyle, ASSEvent } from "./loaders/ass_loader.ts";
export { wordCaptionTrackToAss, vmobjectToAssDrawing } from "./interchange/ass.ts";
export type { AssExportConfig, AssDrawingExportConfig } from "./interchange/ass.ts";
export type { NeuralNetworkConfig, ForwardPassConfig } from "./mobject/neural_network.ts";
export type { DataJoinConfig, DataJoinResult } from "./animation/data_join.ts";
export type { FbmOptions } from "./core/noise.ts";
export { resolveTheme } from "./templates/theme.ts";
export type { Theme, ThemeInput } from "./templates/theme.ts";
export { titleCard, lowerThird, statCounter, socialShort, chartReveal, outroCard } from "./templates/templates.ts";
export type { TemplatePiece } from "./templates/templates.ts";
export { Timeline, timeline } from "./animation/timeline.ts";
export type { TimelineOptions } from "./animation/timeline.ts";
export { Repeat } from "./animation/repeat.ts";
export type { RepeatConfig } from "./animation/repeat.ts";
export { cycle, staggerRange, staggerGrid } from "./animation/stagger.ts";
export type { StaggerGridOptions } from "./animation/stagger.ts";
export { flipGetState, flipFrom } from "./animation/flip.ts";
export type { FlipState, FlipFromConfig } from "./animation/flip.ts";
export { tweenTo, tweenSignal, tween, map, TweenChain, springTween, useRandom, PlopSpring, SmoothSpring, BounceSpring, SwingSpring, JumpSpring, StrikeSpring, } from "./animation/tween_chain.ts";
export type { SeededRandom, Ease } from "./animation/tween_chain.ts";
export { KeyframeTrack, PlayKeyframeTrack, animateSignal } from "./animation/keyframe_track.ts";
export type { Keyframe, KeyframeTrackOptions } from "./animation/keyframe_track.ts";
export { PlayableKeyframeTrack, bindTrack } from "./reactive/keyframes.ts";
export { VectorDecimalNumber, vectorDecimalNumber } from "./mobject/vector_value_tracker.ts";
export type { VectorDecimalNumberConfig } from "./mobject/vector_value_tracker.ts";
export { registerComposition, getComposition, listCompositions, compositionsToJSON, unregisterComposition, } from "./scene/compositions.ts";
export type { CompositionDescriptor } from "./scene/compositions.ts";
export { STYLE_PRESETS, ASPECT_RATIO_PRESETS, resolveStyle, resolveAspectRatio, registerStylePreset, } from "./core/presets.ts";
export type { StylePreset, AspectRatioPreset } from "./core/presets.ts";
export { parseSrt, serializeSrt, createTikTokStyleCaptions, captionAt, } from "./captions/captions.ts";
export type { Caption, CaptionToken, CaptionPage } from "./captions/captions.ts";
export { CaptionTrack, WordCaptionTrack } from "./captions/caption_track.ts";
export type { CaptionTrackConfig, WordCaptionTrackConfig, WordHighlightConfig } from "./captions/caption_track.ts";
export { getAudioData, visualizeAudio, getWaveformPortion, createSmoothSvgPath } from "./audio/analyze.ts";
export type { AudioData } from "./audio/analyze.ts";
export { fftInPlace, magnitudeSpectrum, nextPow2 } from "./audio/fft.ts";
export { rationalTime, rtSeconds, timeRange, toOtioJSON, fromOtioJSON, sceneToOtio, sceneToOtioString, } from "./interchange/otio.ts";
export type { RationalTime, TimeRange, OtioClip, OtioTrack, OtioTimeline } from "./interchange/otio.ts";
export { vmobjectToLottieShapes, lottieShapeToPoints, lottieShapesToVMobject, vmobjectToLottieJSON, loadLottieShapes, } from "./interchange/lottie.ts";
export type { LottieShape, LottieExportOptions } from "./interchange/lottie.ts";
export { electricFieldFunc, magneticFieldFunc, ElectricField, MagneticField, thinLensRefract, } from "./physics/fields.ts";
export type { PointCharge, PointCurrent } from "./physics/fields.ts";
export { WaveCurve, LinearWave, StandingWave } from "./physics/waves.ts";
export type { WaveConfig } from "./physics/waves.ts";
export { SimpleEngine, physics, Pendulum } from "./physics/rigid.ts";
export type { PhysicsBody, PhysicsEngineOptions, PhysicsEngineLike, PendulumConfig } from "./physics/rigid.ts";
export { interpolate } from "./animation/interpolate.ts";
export type { Extrapolation, InterpolateOptions } from "./animation/interpolate.ts";
export { spring, measureSpring, springRate } from "./animation/spring.ts";
export type { SpringConfig, SpringParams } from "./animation/spring.ts";
export { Easing } from "./animation/easing.ts";
export type { EaseFn } from "./animation/easing.ts";
export { Sequence, SequenceAnimation } from "./animation/sequence.ts";
export type { SequenceConfig } from "./animation/sequence.ts";
export { crossFade, slide, wipe, Slide, Wipe, linearTiming, springTiming } from "./animation/transitions.ts";
export type { TransitionConfig, TimingPreset, TimingPresetResult } from "./animation/transitions.ts";
export { delayRender, continueRender, delayRenderUntil, waitForRender, getPendingRenders, } from "./core/async_gate.ts";
export type { DelayHandle } from "./core/async_gate.ts";
export { defineSchema } from "./core/schema.ts";
export type { Schema, SchemaSpec, FieldSpec, FieldType } from "./core/schema.ts";
export { resolveSceneMetadata } from "./scene/scene_params.ts";
export type { SceneMetadata, CalculateMetadata } from "./scene/scene_params.ts";
export { loadWasm, isWasmLoaded, bezierEvalWasm, earclipWasm, mat3VecWasm } from "./wasm.ts";
export { loadManifest, loadManifestFromFile } from "./plugins/manifest.ts";
export { compileExpr, evalExpr } from "./plugins/expr.ts";
export { use, registry, Registry } from "./plugins/registry.ts";
export type { Plugin, PluginLike, RegistryKind } from "./plugins/registry.ts";
export declare const QUALITIES: Record<string, {
    pixelWidth: number;
    pixelHeight: number;
    fps: number;
}>;
//# sourceMappingURL=index.d.ts.map